package scheduler;

@SuppressWarnings("serial")
public class SchedulerGUI extends javax.swing.JFrame 
{
	/**
     * Creates new form SchedulerGUI
     */
	public SchedulerGUI()
	{
		initComponents();
	}
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	public void initComponents() 
	{
		this.setTitle("Scheduler");
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		pack();
	}
}
